apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-api.fullname" . }}
  labels:
    {{- include "portal-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      name: api
    - port: {{ .Values.service.agentPort }}
      targetPort: agent
      name: agent
  selector:
    app.kubernetes.io/name: {{ include "portal-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
