// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields into out.
func (in *CatalogPackage) DeepCopyInto(out *CatalogPackage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of CatalogPackage.
func (in *CatalogPackage) DeepCopy() *CatalogPackage {
	if in == nil {
		return nil
	}
	out := new(CatalogPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CatalogPackage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CatalogPackageList) DeepCopyInto(out *CatalogPackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CatalogPackageList.
func (in *CatalogPackageList) DeepCopy() *CatalogPackageList {
	if in == nil {
		return nil
	}
	out := new(CatalogPackageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CatalogPackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CatalogPackageSpec) DeepCopyInto(out *CatalogPackageSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of CatalogPackageSpec.
func (in *CatalogPackageSpec) DeepCopy() *CatalogPackageSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogPackageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *CatalogPackageStatus) DeepCopyInto(out *CatalogPackageStatus) {
	*out = *in
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of CatalogPackageStatus.
func (in *CatalogPackageStatus) DeepCopy() *CatalogPackageStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogPackageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *CatalogRelease) DeepCopyInto(out *CatalogRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of CatalogRelease.
func (in *CatalogRelease) DeepCopy() *CatalogRelease {
	if in == nil {
		return nil
	}
	out := new(CatalogRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CatalogRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CatalogReleaseList) DeepCopyInto(out *CatalogReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of CatalogReleaseList.
func (in *CatalogReleaseList) DeepCopy() *CatalogReleaseList {
	if in == nil {
		return nil
	}
	out := new(CatalogReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *CatalogReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *CatalogReleaseSpec) DeepCopyInto(out *CatalogReleaseSpec) {
	*out = *in
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]ReleasePackage, len(*in))
		copy(*out, *in)
	}
	if in.CVEReport != nil {
		in, out := &in.CVEReport, &out.CVEReport
		*out = new(CVEReport)
		**out = **in
	}
}

// DeepCopy returns a deep copy of CatalogReleaseSpec.
func (in *CatalogReleaseSpec) DeepCopy() *CatalogReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *CatalogReleaseStatus) DeepCopyInto(out *CatalogReleaseStatus) {
	*out = *in
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of CatalogReleaseStatus.
func (in *CatalogReleaseStatus) DeepCopy() *CatalogReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *CVEReport) DeepCopyInto(out *CVEReport) {
	*out = *in
}

// DeepCopy returns a deep copy of CVEReport.
func (in *CVEReport) DeepCopy() *CVEReport {
	if in == nil {
		return nil
	}
	out := new(CVEReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *ReleasePackage) DeepCopyInto(out *ReleasePackage) {
	*out = *in
}

// DeepCopy returns a deep copy of ReleasePackage.
func (in *ReleasePackage) DeepCopy() *ReleasePackage {
	if in == nil {
		return nil
	}
	out := new(ReleasePackage)
	in.DeepCopyInto(out)
	return out
}
